source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/wayde191/IHakulaSpecs.git'

platform :ios, '7.1'

# BBQ common dependencies
def commonPods
    pod 'IHakulaInfrastructure', :path => '/Users/CNwwsun/iHakula/IHakulaInfrastructure'
end


target 'iHakulaImageView' do
    commonPods
end

target 'iHakulaImageViewTests' do
    commonPods
end

