source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/wayde191/IHakulaSpecs.git'

platform :ios, '7.1'

# BBQ common dependencies
def commonPods
    pod 'IHakulaInfrastructure', '~> 0.2.0'
    pod 'Reachability'
end

target 'iHakulaImageView' do
    commonPods
end

target 'iHakulaImageViewTests' do
    commonPods
end

